security:
    enable_authenticator_manager: true

    firewalls:
        main:
            custom_authenticators:
                - RecruitmentApp\Framework\Security\ApiKeyAuthenticator
    access_control:
      - { path: ^/articles, roles: ROLE_USER }
      - { path: ^/users, roles: ROLE_USER, methods: [DELETE]}
